export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const INCREMENT_PRODUCT_CART_COUNT = 'INCREMENT_PRODUCT_CART_COUNT';
export const DECREMENT_PRODUCT_CART_COUNT = 'DECREMENT_PRODUCT_CART_COUNT';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_CLEAR_ITEMS = 'CART_CLEAR_ITEMS';